package word;

public enum WordType {
    IDENFR, INTCON, STRCON, CONSTTK, INTTK,
    BREAKTK, CONTINUETK, IFTK, ELSETK, NOT, AND, OR,
    WHILETK, PRINTFTK, RETURNTK, PLUS, MINU,
    VOIDTK, ASSIGN, SEMICN, COMMA, LPARENT, RPARENT,
    LBRACK, RBRACK, LBRACE, RBRACE, MULT, DIV, MOD,
    LSS, LEQ, GRE, GEQ, EQL, NEQ, FLOATTK, FLOATCON
}
